DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;

CREATE TABLE KUNDE (
    KUNDENNR INT NOT NULL PRIMARY KEY,
    NACHNAME VARCHAR(50),
    VORNAME VARCHAR(50),
    GEBURTSDATUM DATE,
    STRASSE VARCHAR(50),
    HAUSNR VARCHAR(6),
    PLZ VARCHAR(5),
    ORT VARCHAR(50),
    TELEFON VARCHAR(25),
    EMAIL VARCHAR(50)
);

CREATE TABLE ZUTAT (
    ZUTATENNR INTEGER NOT NULL PRIMARY KEY,
    REZEPTZUTATENNR INT,
    BEZEICHNUNG VARCHAR(50),
    EINHEIT VARCHAR(25),
    NETTOPREIS DECIMAL(10 , 2 ),
    BESTAND INTEGER,
    LIEFERANT INTEGER,
    KALORIEN INTEGER,
    KOHLENHYDRATE DECIMAL(10 , 2 ),
    PROTEIN DECIMAL(10 , 2 )
);
CREATE TABLE REZEPTZUTAT (
	REZEPTNR INT,
    REZEPTZUTATENNR INT NOT NULL PRIMARY KEY,
    ZUTATENNR INT
);

CREATE TABLE REZEPTBESTELL (
	REZEPTBESTELLNR INT NOT NULL PRIMARY KEY,
    BESTELLNR INT,
    REZEPTNR INT
);

CREATE TABLE REZEPT (
	REZEPTNR INT NOT NULL PRIMARY KEY,
    BEZEICHNUNG VARCHAR(50),
    REZEPTZUTAT INT,
    VEGETARISCH BOOL,
    VEGAN BOOL,
    LOWCARB BOOL,
    PESKETARISCH BOOL,
    GLUTENFREI BOOL,
    LAKTOSEFREI BOOL
);

CREATE TABLE BESTELLUNG (
    BESTELLNR INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR INTEGER,
    BESTELLDATUM DATE,
    RECHNUNGSBETRAG DECIMAL(10 , 2 ),
    PRIMARY KEY (BESTELLNR)
);

CREATE TABLE BESTELLZUTAT (
    BESTELLNR INTEGER NOT NULL,
    ZUTATENNR INTEGER PRIMARY KEY,
    MENGE INTEGER
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR INTEGER NOT NULL PRIMARY KEY,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE VARCHAR(50),
    HAUSNR VARCHAR(6),
    PLZ VARCHAR(5),
    ORT VARCHAR(50),
    TELEFON VARCHAR(25),
    EMAIL VARCHAR(50)
);

/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ZUTAT ADD FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR);
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR);
ALTER TABLE BESTELLZUTAT ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE BESTELLZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT(ZUTATENNR);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPT(REZEPTNR);
ALTER TABLE REZEPTBESTELL ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE REZEPTBESTELL ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR);


